DROP DATABASE IF EXISTS P102_01_challange1_nba;
CREATE DATABASE P102_01_challange1_nba; -- !40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */
USE P102_01_challange1_nba;

DROP TABLE IF EXISTS PERSON;
CREATE TABLE PERSON (
    id int(4) AUTO_INCREMENT,   -- AUTO_INCREMENT
    brithdate DATE NOT NULL -- ASSUMPTION
);

DROP TABLE IF EXISTS TEAM_STAFF;
CREATE TABLE TEAM_STAFF (
    team_staff_id int(4) NOT NULL,
    name VARCHAR(50),
    surname VARCHAR(50),

);